#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const appRoot = path.resolve(__dirname, "..", "..");
const androidRoot = path.join(appRoot, "android");
const autolinkingConfigPath = path.join(
  androidRoot,
  "build",
  "generated",
  "autolinking",
  "autolinking.json",
);
const outputDir = path.join(
  androidRoot,
  "app",
  "build",
  "generated",
  "autolinking",
  "src",
  "main",
  "jni",
);

if (!fs.existsSync(autolinkingConfigPath)) {
  throw new Error(`Autolinking config not found at ${autolinkingConfigPath}`);
}

const model = JSON.parse(fs.readFileSync(autolinkingConfigPath, "utf8"));
const androidDeps = Object.values(model.dependencies || {})
  .map((dependency) => dependency?.platforms?.android)
  .filter(Boolean);

const dirExistsForCmake = (cmakeListsPath) => {
  if (!cmakeListsPath) {
    return false;
  }
  const resolvedPath = path.resolve(cmakeListsPath);
  const nativeDir = resolvedPath.replace(/CMakeLists\.txt$/u, "");
  return fs.existsSync(resolvedPath) && fs.statSync(resolvedPath).isFile() && fs.existsSync(nativeDir);
};

const hasJavaCodegen = (dep) => Boolean(dep.libraryName && dirExistsForCmake(dep.cmakeListsPath));
const hasCxxCodegen = (dep) =>
  Boolean(dep.cxxModuleCMakeListsModuleName && dirExistsForCmake(dep.cxxModuleCMakeListsPath));

const packages = androidDeps.filter((dep) => hasJavaCodegen(dep) || hasCxxCodegen(dep));
const skipped = androidDeps
  .filter((dep) => !packages.includes(dep))
  .filter((dep) => dep.libraryName || dep.cxxModuleCMakeListsModuleName);

const sanitizeCmakeListsPath = (cmakeListsPath) =>
  cmakeListsPath.replace(/CMakeLists\.txt$/u, "").replace(/ /gu, "\\ ");

const libraryIncludes = packages
  .map((dep) => {
    const lines = [];
    if (hasJavaCodegen(dep)) {
      lines.push(
        `add_subdirectory("${sanitizeCmakeListsPath(dep.cmakeListsPath)}" ${dep.libraryName}_autolinked_build)`,
      );
    }
    if (hasCxxCodegen(dep)) {
      lines.push(
        `add_subdirectory("${sanitizeCmakeListsPath(dep.cxxModuleCMakeListsPath)}" ${dep.libraryName}_cxxmodule_autolinked_build)`,
      );
    }
    return lines.join("\n");
  })
  .filter(Boolean)
  .join("\n");

const libraryModules = packages
  .map((dep) => {
    const libs = [];
    if (hasJavaCodegen(dep)) {
      libs.push(`react_codegen_${dep.libraryName}`);
    }
    if (hasCxxCodegen(dep)) {
      libs.push(dep.cxxModuleCMakeListsModuleName);
    }
    return libs.join("\n  ");
  })
  .filter(Boolean)
  .join("\n  ");

const packagesWithLibraryNames = packages.filter(hasJavaCodegen);

const cppIncludes = packagesWithLibraryNames
  .map((dep) => {
    let include = `#include <${dep.libraryName}.h>`;
    if (Array.isArray(dep.componentDescriptors) && dep.componentDescriptors.length > 0) {
      include += `\n#include <react/renderer/components/${dep.libraryName}/ComponentDescriptors.h>`;
    }
    if (dep.cxxModuleHeaderName) {
      include += `\n#include <${dep.cxxModuleHeaderName}.h>`;
    }
    return include;
  })
  .join("\n");

const cppTurboModuleJavaProviders = packagesWithLibraryNames
  .map(
    (dep) => `auto module_${dep.libraryName} = ${dep.libraryName}_ModuleProvider(moduleName, params);
if (module_${dep.libraryName} != nullptr) {
return module_${dep.libraryName};
}`,
  )
  .join("\n");

const cppTurboModuleCxxProviders = packagesWithLibraryNames
  .filter((dep) => dep.cxxModuleHeaderName)
  .map(
    (dep) => `if (moduleName == ${dep.cxxModuleHeaderName}::kModuleName) {
return std::make_shared<${dep.cxxModuleHeaderName}>(jsInvoker);
}`,
  )
  .join("\n");

const cppComponentDescriptors = packagesWithLibraryNames
  .filter((dep) => Array.isArray(dep.componentDescriptors) && dep.componentDescriptors.length > 0)
  .flatMap((dep) => dep.componentDescriptors.map((descriptor) => `providerRegistry->add(concreteComponentDescriptorProvider<${descriptor}>());`))
  .join("\n");

const cmakeTemplate = `# This code was generated by a production-safe Aline2 autolinking filter.
cmake_minimum_required(VERSION 3.13)
set(CMAKE_VERBOSE_MAKEFILE on)

# We set REACTNATIVE_MERGED_SO so libraries/apps can selectively decide to depend on either libreactnative.so
# or link against a old prefab target (this is needed for React Native 0.76 on).
set(REACTNATIVE_MERGED_SO true)

${libraryIncludes}

set(AUTOLINKED_LIBRARIES
  ${libraryModules}
)
`;

const cppTemplate = `/**
 * This code was generated by a production-safe Aline2 autolinking filter.
 */

#include "autolinking.h"
${cppIncludes}

namespace facebook {
namespace react {

std::shared_ptr<TurboModule> autolinking_ModuleProvider(const std::string moduleName, const JavaTurboModule::InitParams &params) {
${cppTurboModuleJavaProviders}
  return nullptr;
}

std::shared_ptr<TurboModule> autolinking_cxxModuleProvider(const std::string moduleName, const std::shared_ptr<CallInvoker>& jsInvoker) {
${cppTurboModuleCxxProviders}
  return nullptr;
}

void autolinking_registerProviders(std::shared_ptr<ComponentDescriptorProviderRegistry const> providerRegistry) {
${cppComponentDescriptors}
  return;
}

} // namespace react
} // namespace facebook
`;

const hTemplate = `/**
 * This code was generated by a production-safe Aline2 autolinking filter.
 */

#pragma once

#include <ReactCommon/CallInvoker.h>
#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h>

namespace facebook {
namespace react {

std::shared_ptr<TurboModule> autolinking_ModuleProvider(const std::string moduleName, const JavaTurboModule::InitParams &params);
std::shared_ptr<TurboModule> autolinking_cxxModuleProvider(const std::string moduleName, const std::shared_ptr<CallInvoker>& jsInvoker);
void autolinking_registerProviders(std::shared_ptr<ComponentDescriptorProviderRegistry const> providerRegistry);

} // namespace react
} // namespace facebook
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(path.join(outputDir, "Android-autolinking.cmake"), cmakeTemplate);
fs.writeFileSync(path.join(outputDir, "autolinking.cpp"), cppTemplate);
fs.writeFileSync(path.join(outputDir, "autolinking.h"), hTemplate);

if (skipped.length > 0) {
  const skippedNames = skipped.map((dep) => dep.libraryName || dep.cxxModuleCMakeListsModuleName).join(", ");
  throw new Error(
    `Filtered missing Android codegen deps: ${skippedNames}. Prewarm dependency codegen before generating Android autolinking files.`,
  );
}

console.log("No Android codegen deps needed filtering.");
